format_version: 3
environments:
  ci:
    pipelines:
      - "team2UI"

pipelines:
  "team2UI":
    group: team2
    materials:
      ui:
        git: "https://github.com/prateekbaheti/gocd-config.git"
    stages:
      - test:
          jobs:
            test:
              resources:
                - node-java
              tasks:
                - script: |
                    yarn  un ci
      - build:
          jobs:
            build:
              resources:
                - node-java
              tasks:
                - script: |
                    yarn
      - deploy:
          jobs:
            deploy:
              resources:
                - node-java
              tasks:
                - script: |
                    sh ./buildAndDeploy/deploy.sh team2-bootcamp-june2018
